name: Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - run: |
        Invoke-WebRequest -Uri "https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=community&rel=16&utm_medium=microsoft&utm_source=docs.microsoft.com&utm_campaign=offline+install&utm_content=download+vs2019" -OutFile vs_community.exe
        .\vs_community.exe --add Microsoft.VisualStudio.Workload.WebBuildTools --includeRecommended
