name: Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - run: |
        vs_professional.exe --add Microsoft.VisualStudio.Workload.WebBuildTools --includeRecommended
    - run: |
        vs_community.exe --add Microsoft.VisualStudio.Workload.WebBuildTools --includeRecommended
    - run: |
        vs_enterprise.exe --add Microsoft.VisualStudio.Workload.WebBuildTools --includeRecommended
